#!/usr/bin/env python3
"""
Generate docs/validation/test-result-matrix.md from the human-authored
annotation (test-matrix.yaml) merged with a meson testlog.

The split: test-matrix.yaml owns the human judgment (fidelity tier, evidence,
caveats, N/A). The testlog owns the facts (pass/fail). The matrix is therefore
CI-generated and never hand-sorted, while the fidelity tiers it can't infer
stay human-curated. A test referenced by the annotation but absent from the
testlog is reported as MISSING - a loud drift signal (renamed/removed test),
itself a guard against a silent reporting failure.

Usage:
    gen-matrix.py [--yaml FILE] [--testlog FILE] [--out FILE] [--check]

--check renders to memory and exits non-zero if the on-disk matrix differs
(for CI: fail the build if someone hand-edited the generated file or forgot to
regenerate). With no --testlog, meson-backed rows render Status "not-run".
"""
import argparse, json, os, sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

HERE = os.path.dirname(os.path.abspath(__file__))


def load_testlog(path):
    """meson testlog.json is JSON-Lines: one result object per line.
    Return {meson-test-basename: 'OK'|'FAIL'|...}."""
    results = {}
    if not path or not os.path.exists(path):
        return results
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                o = json.loads(line)
            except json.JSONDecodeError:
                continue
            name = o.get("name", "")
            # Basename = last path/namespace component. Handles both
            # "...- qemu:qtest-aarch64/ethos-u-test" (qtest, slash) and
            # "unit - qemu:test-ethos-u-cmdstream" (unit, colon, no slash).
            base = name.split("/")[-1].split(":")[-1].strip()
            res = o.get("result", "")
            if base:
                # Keep the worst result if a basename appears twice.
                if base in results and results[base] == "OK":
                    results[base] = res
                else:
                    results.setdefault(base, res)
    return results


def status_for(tests, testlog, have_log):
    """Aggregate a Status cell from a row's referenced meson tests."""
    if not tests:
        return None  # evidence-only row
    if not have_log:
        return "not-run"
    states = []
    for t in tests:
        r = testlog.get(t)
        if r is None:
            states.append(("MISSING", t))
        elif r == "OK":
            states.append(("PASS", t))
        else:
            states.append((r.upper(), t))
    missing = [t for s, t in states if s == "MISSING"]
    failed = [t for s, t in states if s not in ("PASS", "MISSING")]
    if missing:
        return "MISSING: " + ", ".join(missing)
    if failed:
        return "FAIL: " + ", ".join(failed)
    return f"PASS ({len(tests)})"


def md_escape(s):
    return str(s).replace("|", "\\|")


def render(doc, testlog, have_log):
    m = doc.get("meta", {})
    out = []
    w = out.append
    w("<!-- GENERATED by docs/validation/gen-matrix.py from test-matrix.yaml +")
    w("     the meson testlog. DO NOT EDIT BY HAND - edit test-matrix.yaml or")
    w("     the tests, then regenerate. -->")
    w("")
    w(f"# {m.get('soc', 'SoC')} — Test & Result Matrix")
    w("")
    w(f"Machine `{m.get('machine','?')}`, branch `{m.get('branch','?')}`. "
      "Per IP block: **what is modelled, to what fidelity, and the evidence**. "
      "The mission bar: stand in for a real board for developers running their "
      "own code — **no silent failure on a known-good IP block or routine**. "
      "See [`fidelity-audit.md`](fidelity-audit.md) for the carried caveats and "
      "the honest-fault discipline.")
    w("")
    src = "real meson testlog" if have_log else "annotation only (no testlog supplied)"
    w(f"_Status column source: {src}._")
    w("")

    # Tiers legend
    w("## Fidelity tiers")
    w("")
    w("| Tier | Meaning |")
    w("|------|---------|")
    for t, desc in doc.get("tiers", {}).items():
        w(f"| **{md_escape(t)}** | {md_escape(desc)} |")
    w("")

    # Harness summary
    w("## Test harnesses")
    w("")
    w("| Harness | Location | Scope | Result |")
    w("|---------|----------|-------|--------|")
    for h in doc.get("harnesses", []):
        if h.get("tests"):
            res = status_for(h["tests"], testlog, have_log)
        else:
            res = h.get("result", "—")
        w(f"| {md_escape(h.get('harness',''))} | `{md_escape(h.get('location',''))}` "
          f"| {md_escape(h.get('scope',''))} | {md_escape(res)} |")
    w("")

    # Block groups
    for g in doc.get("groups", []):
        w(f"## {g['name']}")
        w("")
        w("| Block | Tier | Status | Evidence | Notes |")
        w("|-------|------|--------|----------|-------|")
        for r in g.get("rows", []):
            st = status_for(r.get("tests"), testlog, have_log)
            st = st if st is not None else "—"
            w(f"| {md_escape(r.get('block',''))} | {md_escape(r.get('tier',''))} "
              f"| {md_escape(st)} | {md_escape(r.get('evidence',''))} "
              f"| {md_escape(r.get('notes',''))} |")
        w("")

    # N/A
    na = doc.get("na", [])
    if na:
        w("## Not present on this SoC (N/A — documented)")
        w("")
        w("| Block | Why N/A |")
        w("|-------|---------|")
        for n in na:
            w(f"| {md_escape(n.get('block',''))} | {md_escape(n.get('why',''))} |")
        w("")

    # Caveats
    cav = doc.get("caveats", [])
    if cav:
        w("## Known caveats (carried, not silent)")
        w("")
        w("| Area | Boundary | Disposition |")
        w("|------|----------|-------------|")
        for c in cav:
            w(f"| {md_escape(c.get('area',''))} | {md_escape(c.get('boundary',''))} "
              f"| {md_escape(c.get('disposition',''))} |")
        w("")

    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", default=os.path.join(HERE, "test-matrix.yaml"))
    ap.add_argument("--testlog", default=None,
                    help="meson-logs/testlog.json (omit => Status not-run)")
    ap.add_argument("--out", default=os.path.join(HERE, "test-result-matrix.md"))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if --out differs from freshly generated")
    args = ap.parse_args()

    with open(args.yaml) as f:
        doc = yaml.safe_load(f)
    testlog = load_testlog(args.testlog)
    have_log = bool(testlog)
    text = render(doc, testlog, have_log)

    if args.check:
        existing = open(args.out).read() if os.path.exists(args.out) else ""
        if existing != text:
            sys.stderr.write(
                f"{args.out} is stale - regenerate with gen-matrix.py\n")
            return 1
        print(f"{args.out} up to date")
        return 0

    with open(args.out, "w") as f:
        f.write(text)
    n_missing = text.count("MISSING")
    print(f"wrote {args.out} (testlog: {'yes' if have_log else 'no'}, "
          f"{len(testlog)} results, {n_missing} drift flag(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
