#!/usr/bin/env python3
"""
Generate docs/validation/test-result-matrix.md from the human-authored
annotation (test-matrix.yaml) merged with a meson testlog.

The split: test-matrix.yaml owns the human judgment (fidelity tier, evidence,
caveats, N/A). The testlog owns the facts (pass/fail). The matrix is therefore
CI-generated and never hand-sorted, while the fidelity tiers it can't infer
stay human-curated. A test referenced by the annotation but absent from the
testlog is reported as MISSING - a loud drift signal (renamed/removed test),
itself a guard against a silent reporting failure.

Usage:
    gen-matrix.py [--yaml FILE] [--testlog FILE] [--out FILE] [--check]

--check renders to memory and exits non-zero if the on-disk matrix differs
(for CI: fail the build if someone hand-edited the generated file or forgot to
regenerate). With no --testlog, meson-backed rows render Status "not-run".
"""
import argparse, json, os, sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

HERE = os.path.dirname(os.path.abspath(__file__))


def load_testlog(path):
    """meson testlog.json is JSON-Lines: one result object per line.
    Return {meson-test-basename: 'OK'|'FAIL'|...}."""
    results = {}
    if not path or not os.path.exists(path):
        return results
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                o = json.loads(line)
            except json.JSONDecodeError:
                continue
            name = o.get("name", "")
            # Basename = last path/namespace component. Handles both
            # "...- qemu:qtest-aarch64/ethos-u-test" (qtest, slash) and
            # "unit - qemu:test-ethos-u-cmdstream" (unit, colon, no slash).
            base = name.split("/")[-1].split(":")[-1].strip()
            res = o.get("result", "")
            if base:
                # Keep the worst result if a basename appears twice.
                if base in results and results[base] == "OK":
                    results[base] = res
                else:
                    results.setdefault(base, res)
    return results


def status_for(tests, testlog, have_log):
    """Aggregate a Status cell from a row's referenced meson tests."""
    if not tests:
        return None  # evidence-only row
    if not have_log:
        return "not-run"
    states = []
    for t in tests:
        r = testlog.get(t)
        if r is None:
            states.append(("MISSING", t))
        elif r == "OK":
            states.append(("PASS", t))
        else:
            states.append((r.upper(), t))
    missing = [t for s, t in states if s == "MISSING"]
    failed = [t for s, t in states if s not in ("PASS", "MISSING")]
    if missing:
        return "MISSING: " + ", ".join(missing)
    if failed:
        return "FAIL: " + ", ".join(failed)
    return f"PASS ({len(tests)})"


def md_escape(s):
    return str(s).replace("|", "\\|")


def render(doc, testlog, have_log):
    m = doc.get("meta", {})
    out = []
    w = out.append
    w("<!-- GENERATED by docs/validation/gen-matrix.py from test-matrix.yaml +")
    w("     the meson testlog. DO NOT EDIT BY HAND - edit test-matrix.yaml or")
    w("     the tests, then regenerate. -->")
    w("")
    w(f"# {m.get('soc', 'SoC')} — Test & Result Matrix")
    w("")
    w(f"Machine `{m.get('machine','?')}`, branch `{m.get('branch','?')}`. "
      "Per IP block: **what is modelled, to what fidelity, and the evidence**. "
      "The mission bar: stand in for a real board for developers running their "
      "own code — **no silent failure on a known-good IP block or routine**. "
      "See [`fidelity-audit.md`](fidelity-audit.md) for the carried caveats and "
      "the honest-fault discipline.")
    w("")
    src = "real meson testlog" if have_log else "annotation only (no testlog supplied)"
    w(f"_Status column source: {src}._")
    w("")

    # Tiers legend
    w("## Fidelity tiers")
    w("")
    w("| Tier | Meaning |")
    w("|------|---------|")
    for t, desc in doc.get("tiers", {}).items():
        w(f"| **{md_escape(t)}** | {md_escape(desc)} |")
    w("")

    # Harness summary
    w("## Test harnesses")
    w("")
    w("| Harness | Location | Scope | Result |")
    w("|---------|----------|-------|--------|")
    for h in doc.get("harnesses", []):
        if h.get("tests"):
            res = status_for(h["tests"], testlog, have_log)
        else:
            res = h.get("result", "—")
        w(f"| {md_escape(h.get('harness',''))} | `{md_escape(h.get('location',''))}` "
          f"| {md_escape(h.get('scope',''))} | {md_escape(res)} |")
    w("")

    # Block groups
    for g in doc.get("groups", []):
        w(f"## {g['name']}")
        w("")
        w("| Block | Tier | Status | Evidence | Notes |")
        w("|-------|------|--------|----------|-------|")
        for r in g.get("rows", []):
            st = status_for(r.get("tests"), testlog, have_log)
            st = st if st is not None else "—"
            w(f"| {md_escape(r.get('block',''))} | {md_escape(r.get('tier',''))} "
              f"| {md_escape(st)} | {md_escape(r.get('evidence',''))} "
              f"| {md_escape(r.get('notes',''))} |")
        w("")

    # N/A
    na = doc.get("na", [])
    if na:
        w("## Not present on this SoC (N/A — documented)")
        w("")
        w("| Block | Why N/A |")
        w("|-------|---------|")
        for n in na:
            w(f"| {md_escape(n.get('block',''))} | {md_escape(n.get('why',''))} |")
        w("")

    # Caveats
    cav = doc.get("caveats", [])
    if cav:
        w("## Known caveats (carried, not silent)")
        w("")
        w("| Area | Boundary | Disposition |")
        w("|------|----------|-------------|")
        for c in cav:
            w(f"| {md_escape(c.get('area',''))} | {md_escape(c.get('boundary',''))} "
              f"| {md_escape(c.get('disposition',''))} |")
        w("")

    return "\n".join(out) + "\n"


# ---- README condensed capability table (same YAML, second rendering) --------
REPO = os.path.dirname(os.path.dirname(HERE))
README_BEGIN = "<!-- BEGIN capability-table (generated from test-matrix.yaml) -->"
README_END = "<!-- END capability-table (generated from test-matrix.yaml) -->"


def _present_tiers(doc):
    """{block name: tier} for every per-block row across all groups."""
    out = {}
    for g in doc.get("groups", []):
        for r in g.get("rows", []):
            out[r["block"]] = r["tier"]
    return out


def verify_groups(doc):
    """Every present/absent block is grouped exactly once; groups are single-tier.

    The anti-drift guard: the README condensed table and the detailed matrix
    render from the same blocks, so a block added/removed/re-tiered in the YAML
    must be reflected in a readme_group or generation fails.
    """
    present = _present_tiers(doc)
    absent = {n["block"] for n in doc.get("na", [])}
    seen_p, seen_a, errs = [], [], []
    for g in doc.get("readme_groups", []):
        for b in g["blocks"]:
            seen_p.append(b)
            if b not in present:
                errs.append(f"readme_group '{g['label']}' lists unknown block {b}")
            elif present[b] != g["tier"]:
                errs.append(f"'{b}' is tier {present[b]} but group "
                            f"'{g['label']}' is tier {g['tier']}")
    for g in doc.get("readme_absent", []):
        for b in g["blocks"]:
            seen_a.append(b)
            if b not in absent:
                errs.append(f"readme_absent lists unknown block {b}")
    for b in present:
        if seen_p.count(b) != 1:
            errs.append(f"present block '{b}' grouped {seen_p.count(b)}x (want 1)")
    for b in absent:
        if seen_a.count(b) != 1:
            errs.append(f"absent block '{b}' grouped {seen_a.count(b)}x (want 1)")
    if errs:
        raise SystemExit("readme_group drift:\n  " + "\n  ".join(errs))


def render_readme_capability(doc):
    out = ["| Subsystem | Tier | Evidence |", "|---|:--:|---|"]
    for g in doc.get("readme_groups", []):
        out.append(f"| {g['label']} | {g['tier']} | {g.get('evidence', '')} |")
    out += ["", "**Absent on i.MX 93 silicon — N/A (never a failure):**", "",
            "| Block | Why absent |", "|---|---|"]
    for g in doc.get("readme_absent", []):
        out.append(f"| {g['label']} | {g['reason']} |")
    return "\n".join(out)


def inject_readme(doc, path):
    verify_groups(doc)
    text = open(path).read()
    if README_BEGIN not in text or README_END not in text:
        raise SystemExit(f"{path}: missing capability-table markers")
    head, rest = text.split(README_BEGIN, 1)
    _, tail = rest.split(README_END, 1)
    block = f"{README_BEGIN}\n{render_readme_capability(doc)}\n{README_END}"
    new = head + block + tail
    if new != text:
        open(path, "w").write(new)
        sys.stderr.write(f"updated {path} capability table from test-matrix.yaml\n")
        return 1
    sys.stderr.write(f"{path} capability table already in sync\n")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", default=os.path.join(HERE, "test-matrix.yaml"))
    ap.add_argument("--testlog", default=None,
                    help="meson-logs/testlog.json (omit => Status not-run)")
    ap.add_argument("--out", default=os.path.join(HERE, "test-result-matrix.md"))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if --out differs from freshly generated")
    ap.add_argument("--inject-readme", nargs="?",
                    const=os.path.join(REPO, "README.md"),
                    help="regenerate the README capability table from the YAML "
                         "(between the capability-table markers) and exit")
    args = ap.parse_args()

    with open(args.yaml) as f:
        doc = yaml.safe_load(f)

    if args.inject_readme is not None:
        return inject_readme(doc, args.inject_readme)

    testlog = load_testlog(args.testlog)
    have_log = bool(testlog)
    text = render(doc, testlog, have_log)

    if args.check:
        verify_groups(doc)     # anti-drift: README groups cover every block once
        readme = os.path.join(REPO, "README.md")
        if os.path.exists(readme) and README_BEGIN in open(readme).read():
            if inject_readme(doc, readme):
                sys.stderr.write(
                    f"{readme} capability table is stale - "
                    f"run gen-matrix.py --inject-readme\n")
                return 1
        existing = open(args.out).read() if os.path.exists(args.out) else ""
        if existing != text:
            sys.stderr.write(
                f"{args.out} is stale - regenerate with gen-matrix.py\n")
            return 1
        print(f"{args.out} up to date")
        return 0

    with open(args.out, "w") as f:
        f.write(text)
    n_missing = text.count("MISSING")
    print(f"wrote {args.out} (testlog: {'yes' if have_log else 'no'}, "
          f"{len(testlog)} results, {n_missing} drift flag(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
